version: '{build}'

environment:
  global:
    PREFIX_VERSION: 20180708

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VisualStudioVersion: 12.0
      CMAKE_GENERATOR: Visual Studio 12 2013
      PYTHON_PREFIX: C:\Python34
      CMAKE_PARAMS: -DPYTHON_INCLUDE_DIR=C:/Python34/include
        -DPython3_LIBRARY=C:/Python34/libs/python34.lib
        -DPython3_EXECUTABLE=C:/Python34/python.exe
        -DPython3_INCLUDE_DIR=C:/Python34/include
      PREFIX_TARGET: vc2013-x86-static
      DIST_SUFFIX: '%PREFIX_TARGET%-py34'

before_build:
  # Download prefix libs
  - mkdir build_deps && cd build_deps
  - curl -LO https://github.com/H-uru/PlasmaPrefix/releases/download/%PREFIX_VERSION%/prefix-%PREFIX_TARGET%.zip
  - cmake -E tar xf prefix-%PREFIX_TARGET%.zip --format=zip

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - mkdir build && cd build
  - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_PREFIX_PATH="%APPVEYOR_BUILD_FOLDER%/build_deps/prefix-%PREFIX_TARGET%"
      -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%/dist/libhsplasma-%DIST_SUFFIX%"
      -DENABLE_PYTHON=ON -DENABLE_NET=ON -DENABLE_TOOLS=ON -DENABLE_PHYSX=OFF
      %CMAKE_PARAMS% ..
  - cmake --build . --config Release

after_build:
  - cmake --build . --config Release --target INSTALL
  - cd "%APPVEYOR_BUILD_FOLDER%\dist"
  - cmake -E tar cf libhsplasma-%DIST_SUFFIX%.zip --format=zip libhsplasma-%DIST_SUFFIX%

test_script:
  # Basic import test
  - cd "%APPVEYOR_BUILD_FOLDER%\dist\libhsplasma-%DIST_SUFFIX%\bin"
  - "%PYTHON_PREFIX%\\python.exe -c \"import PyHSPlasma; print(dir(PyHSPlasma))\""

artifacts:
  - path: dist\libhsplasma-*.zip
