CC = g++
CFLAGS = -O2 -fPIC -Wall -g -ansi -fno-rtti

all:
	(cd trunk ; make -fMakefile.win)
	make -fMakefile.win Tools/PageConvert.exe
	make -fMakefile.win Tools/PlasmaCrypt.exe
	make -fMakefile.win Tools/PrpPack.exe
	make -fMakefile.win Tools/PrcExtract.exe

Tools/PageConvert.exe: trunk/lib/libPlasma.dll Tools/src/PageConvert.cpp
	$(CC) $(CFLAGS) -Ltrunk/lib/ -lPlasma -Itrunk Tools/src/PageConvert.cpp -o Tools/PageConvert.exe

Tools/PlasmaCrypt.exe: trunk/lib/libPlasma.dll Tools/src/PlasmaCrypt.cpp
	$(CC) $(CFLAGS) -Ltrunk/lib/ -lPlasma -Itrunk -DLEKEY Tools/src/PlasmaCrypt.cpp -o Tools/PlasmaCrypt.exe

Tools/PrpPack.exe: trunk/lib/libPlasma.dll Tools/src/PrpPack.cpp
	$(CC) $(CFLAGS) -Ltrunk/lib/ -lPlasma -Itrunk Tools/src/PrpPack.cpp -o Tools/PrpPack.exe

Tools/PrcExtract.exe: trunk/lib/libPlasma.dll Tools/src/PrcExtract.cpp
	$(CC) $(CFLAGS) -Ltrunk/lib/ -lPlasma -Itrunk Tools/src/PrcExtract.cpp -o Tools/PrcExtract.exe

clean:
	(cd trunk ; make clean)

distclean:
	(cd trunk ; make distclean)
	rm -f Tools/PageConvert.exe
	rm -f Tools/PlasmaCrypt.exe
	rm -f Tools/PrpPack.exe
	rm -f Tools/PrcExtract.exe
