CC = g++
CFLAGS += -fPIC -Wall -g -ansi -fno-rtti

all:
	(cd core ; $(MAKE) -fMakefile.linux)
	(cd Python ; $(MAKE) -fMakefile.linux)
	($(MAKE) -fMakefile.linux Tools/PageConvert)
	($(MAKE) -fMakefile.linux Tools/PlasmaCrypt)
	($(MAKE) -fMakefile.linux Tools/PrpPack)
	($(MAKE) -fMakefile.linux Tools/PrcExtract)
	($(MAKE) -fMakefile.linux Tools/PageList)
	($(MAKE) -fMakefile.linux Tools/prcc)
	($(MAKE) -fMakefile.linux Tools/prcdc)
	($(MAKE) -fMakefile.linux Tools/Prp2Obj)
	($(MAKE) -fMakefile.linux Tools/PageEditor)
	($(MAKE) -fMakefile.linux Misc/TypeMap)

Tools/PageConvert: Tools/src/PageConvert.cpp core/lib/libPlasma.so
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/PageConvert.cpp -o Tools/PageConvert

Tools/PlasmaCrypt: Tools/src/PlasmaCrypt.cpp core/lib/libPlasma.so
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/PlasmaCrypt.cpp -o Tools/PlasmaCrypt

Tools/PrpPack: Tools/src/PrpPack.cpp core/lib/libPlasma.so
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/PrpPack.cpp -o Tools/PrpPack

Tools/PrcExtract: Tools/src/PrcExtract.cpp core/lib/libPlasma.so
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/PrcExtract.cpp -o Tools/PrcExtract

Tools/PageList: Tools/src/PageList.cpp core/lib/libPlasma.so
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/PageList.cpp -o Tools/PageList

Tools/prcc: Tools/src/prcc.cpp core/lib/libPlasma.so
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/prcc.cpp -o Tools/prcc

Tools/prcdc: Tools/src/prcdc.cpp core/lib/libPlasma.so
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/prcdc.cpp -o Tools/prcdc

Tools/Prp2Obj: Tools/src/Prp2Obj.cpp core/lib/libPlasma.so
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/Prp2Obj.cpp -o Tools/Prp2Obj

Tools/PageEditor: PageEditor/PageEditor.cpp PageEditor/ExplorerFrm.cpp PageEditor/CreateFrm.cpp PageEditor/CHexEditCtrl.cpp PageEditor/wxPlasmaTextCtrl.cpp PageEditor/PlasmaTreeItem.cpp core/lib/libPlasma.so
	$(CC) $(CFLAGS) `wx-config --cxxflags --libs std,stc` -Lcore/lib/ -lPlasma -Icore PageEditor/PageEditor.cpp PageEditor/CreateFrm.cpp PageEditor/ExplorerFrm.cpp PageEditor/wxPlasmaTextCtrl.cpp PageEditor/CHexEditCtrl.cpp PageEditor/PlasmaTreeItem.cpp -o Tools/PageEditor

Misc/TypeMap: Misc/TypeMap.cpp core/lib/libPlasma.so
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Misc/TypeMap.cpp -o Misc/TypeMap

install:
	(cd core ; $(MAKE) -fMakefile.linux install)
	cp Tools/PageConvert /usr/local/bin/
	cp Tools/PlasmaCrypt /usr/local/bin/
	cp Tools/PrpPack /usr/local/bin/
	cp Tools/PrcExtract /usr/local/bin/
	cp Tools/PageList /usr/local/bin/
	cp Tools/prcc /usr/local/bin/
	cp Tools/prcdc /usr/local/bin/
	cp Tools/Prp2Obj /usr/local/bin/
	cp Tools/PageEditor /usr/local/bin/
	chmod +x Tools/eoaedit Tools/uruedit
	cp Tools/eoaedit Tools/uruedit /usr/local/bin/
	cp Python/PyPlasma.so /usr/lib/python2.5/

uninstall:
	rm -f /usr/local/bin/PageConvert
	rm -f /usr/local/bin/PlasmaCrypt
	rm -f /usr/local/bin/PrpPack
	rm -f /usr/local/bin/PrcExtract
	rm -f /usr/local/bin/PageList
	rm -f /usr/local/bin/prcc
	rm -f /usr/local/bin/prcdc
	rm -f /usr/local/bin/Prp2Obj
	rm -f /usr/local/bin/PageEditor
	rm -f /usr/local/bin/eoaedit
	rm -f /usr/local/bin/uruedit
	rm -f /usr/lib/python2.5/PyPlasma.so

clean:
	(cd core ; $(MAKE) -fMakefile.linux clean)
	(cd Python ; $(MAKE) -fMakefile.linux clean)

distclean:
	(cd core ; $(MAKE) -fMakefile.linux distclean)
	(cd Python ; $(MAKE) -fMakefile.linux distclean)
	rm -f Tools/PageConvert
	rm -f Tools/PlasmaCrypt
	rm -f Tools/PrpPack
	rm -f Tools/PrcExtract
	rm -f Tools/PageList
	rm -f Tools/prcc
	rm -f Tools/prcdc
	rm -f Tools/Prp2Obj
	rm -f Tools/PageEditor
	rm -f Misc/TypeMap
