CXX = g++
CXXFLAGS += -fPIC -Wall -g -ansi -fno-rtti -arch ppc -arch i386 -DMACOSX

PREFIX = /usr/local
BINDIR = bin

all:
	(cd core ; $(MAKE) -fMakefile.macosx)
	(cd Python ; $(MAKE) -fMakefile.macosx)
	($(MAKE) -fMakefile.macosx $(BINDIR)/PageConvert)
	($(MAKE) -fMakefile.macosx $(BINDIR)/PlasmaCrypt)
	($(MAKE) -fMakefile.macosx $(BINDIR)/PrpPack)
	($(MAKE) -fMakefile.macosx $(BINDIR)/PrcExtract)
	($(MAKE) -fMakefile.macosx $(BINDIR)/PageList)
	($(MAKE) -fMakefile.macosx $(BINDIR)/prcc)
	($(MAKE) -fMakefile.macosx $(BINDIR)/prcdc)
	($(MAKE) -fMakefile.macosx $(BINDIR)/Prp2Obj)
	($(MAKE) -fMakefile.macosx $(BINDIR)/PyPack)
	($(MAKE) -fMakefile.macosx $(BINDIR)/prpmod)
	($(MAKE) -fMakefile.macosx $(BINDIR)/prpgrep)
	($(MAKE) -fMakefile.macosx $(BINDIR)/PlasmaSum)
	($(MAKE) -fMakefile.macosx Misc/TypeMap)

$(BINDIR)/PageConvert: Tools/src/PageConvert.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PageConvert.cpp -o $@

$(BINDIR)/PlasmaCrypt: Tools/src/PlasmaCrypt.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PlasmaCrypt.cpp -o $@

$(BINDIR)/PrpPack: Tools/src/PrpPack.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PrpPack.cpp -o $@

$(BINDIR)/PrcExtract: Tools/src/PrcExtract.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PrcExtract.cpp -o $@

$(BINDIR)/PageList: Tools/src/PageList.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PageList.cpp -o $@

$(BINDIR)/prcc: Tools/src/prcc.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/prcc.cpp -o $@

$(BINDIR)/prcdc: Tools/src/prcdc.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/prcdc.cpp -o $@

$(BINDIR)/Prp2Obj: Tools/src/Prp2Obj.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/Prp2Obj.cpp -o $@

$(BINDIR)/PyPack: Tools/src/PyPack.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PyPack.cpp -o $@

$(BINDIR)/prpmod: Tools/src/prpmod.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/prpmod.cpp -o $@

$(BINDIR)/prpgrep: Tools/src/prpgrep.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/prpgrep.cpp -o $@

$(BINDIR)/PlasmaSum: Tools/src/PlasmaSum.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PlasmaSum.cpp -o $@

Misc/TypeMap: Misc/TypeMap.cpp $(BINDIR)/libPlasma.dylib
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Misc/TypeMap.cpp -o $@

install:
	(cd core ; $(MAKE) -fMakefile.macosx install)
	(cd Python ; $(MAKE) -fMakefile.macosx install)
	cp $(BINDIR)/PageConvert $(PREFIX)/bin/
	cp $(BINDIR)/PlasmaCrypt $(PREFIX)/bin/
	cp $(BINDIR)/PrpPack $(PREFIX)/bin/
	cp $(BINDIR)/PrcExtract $(PREFIX)/bin/
	cp $(BINDIR)/PageList $(PREFIX)/bin/
	cp $(BINDIR)/prcc $(PREFIX)/bin/
	cp $(BINDIR)/prcdc $(PREFIX)/bin/
	cp $(BINDIR)/Prp2Obj $(PREFIX)/bin/
	cp $(BINDIR)/PyPack $(PREFIX)/bin/
	cp $(BINDIR)/prpmod $(PREFIX)/bin/
	cp $(BINDIR)/prpgrep $(PREFIX)/bin/
	cp $(BINDIR)/PlasmaSum $(PREFIX)/bin/
	chmod +x $(BINDIR)/eoaedit $(BINDIR)/uruedit
	cp $(BINDIR)/eoaedit $(BINDIR)/uruedit $(PREFIX)/bin/

uninstall:
	(cd core ; $(MAKE) -fMakefile.macosx uninstall)
	(cd Python ; $(MAKE) -fMakefile.macosx uninstall)
	rm -f $(PREFIX)/bin/PageConvert
	rm -f $(PREFIX)/bin/PlasmaCrypt
	rm -f $(PREFIX)/bin/PrpPack
	rm -f $(PREFIX)/bin/PrcExtract
	rm -f $(PREFIX)/bin/PageList
	rm -f $(PREFIX)/bin/prcc
	rm -f $(PREFIX)/bin/prcdc
	rm -f $(PREFIX)/bin/Prp2Obj
	rm -f $(PREFIX)/bin/PyPack
	rm -f $(PREFIX)/bin/prpmod
	rm -f $(PREFIX)/bin/prpgrep
	rm -f $(PREFIX)/bin/PlasmaSum
	rm -f $(PREFIX)/bin/eoaedit
	rm -f $(PREFIX)/bin/uruedit

clean:
	(cd core ; $(MAKE) -fMakefile.macosx clean)
	(cd Python ; $(MAKE) -fMakefile.macosx clean)

distclean:
	(cd core ; $(MAKE) -fMakefile.macosx distclean)
	(cd Python ; $(MAKE) -fMakefile.macosx distclean)
	rm -f $(BINDIR)/PageConvert
	rm -f $(BINDIR)/PlasmaCrypt
	rm -f $(BINDIR)/PrpPack
	rm -f $(BINDIR)/PrcExtract
	rm -f $(BINDIR)/PageList
	rm -f $(BINDIR)/prcc
	rm -f $(BINDIR)/prcdc
	rm -f $(BINDIR)/Prp2Obj
	rm -f $(BINDIR)/PyPack
	rm -f $(BINDIR)/prpmod
	rm -f $(BINDIR)/prpgrep
	rm -f $(BINDIR)/PlasmaSum
	rm -f Misc/TypeMap
