CC = g++
CFLAGS = -O2 -fPIC -Wall -g -ansi -fno-rtti

all:
	(cd core ; make -fMakefile.win)
	(cd Python ; make -fMakefile.win)
	make -fMakefile.win Tools/PageConvert.exe
	make -fMakefile.win Tools/PlasmaCrypt.exe
	make -fMakefile.win Tools/PrpPack.exe
	make -fMakefile.win Tools/PrcExtract.exe
	make -fMakefile.win Tools/PageList.exe
	make -fMakefile.win Tools/prcc.exe
	make -fMakefile.win Tools/prcdc.exe
	make -fMakefile.win Tools/Prp2Obj.exe
	make -fMakefile.win Tools/PageExplorer.exe
	make -fMakefile.win Misc/TypeMap.exe

Tools/PageConvert.exe: Tools/src/PageConvert.cpp core/lib/libPlasma.dll
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/PageConvert.cpp -o Tools/PageConvert.exe

Tools/PlasmaCrypt.exe: Tools/src/PlasmaCrypt.cpp core/lib/libPlasma.dll
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/PlasmaCrypt.cpp -o Tools/PlasmaCrypt.exe

Tools/PrpPack.exe: Tools/src/PrpPack.cpp core/lib/libPlasma.dll
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/PrpPack.cpp -o Tools/PrpPack.exe

Tools/PrcExtract.exe: Tools/src/PrcExtract.cpp core/lib/libPlasma.dll
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/PrcExtract.cpp -o Tools/PrcExtract.exe

Tools/PageList.exe: Tools/src/PageList.cpp core/lib/libPlasma.dll
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/PageList.cpp -o Tools/PageList.exe

Tools/prcc.exe: Tools/src/prcc.cpp core/lib/libPlasma.dll
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/prcc.cpp -o Tools/prcc.exe

Tools/prcdc.exe: Tools/src/prcdc.cpp core/lib/libPlasma.dll
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/prcdc.cpp -o Tools/prcdc.exe

Tools/Prp2Obj.exe: Tools/src/Prp2Obj.cpp core/lib/libPlasma.dll
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Tools/src/Prp2Obj.cpp -o Tools/Prp2Obj.exe

Tools/PageExplorer.exe: PageExplorer/PageExplorer.cpp PageExplorer/ExplorerFrm.cpp PageExplorer/wxPlasmaTextCtrl.cpp core/lib/libPlasma.dll
	$(CC) $(CFLAGS) `wx-config --cxxflags --libs std,stc` -Lcore/lib/ -lPlasma -Icore PageExplorer/PageExplorer.cpp PageExplorer/ExplorerFrm.cpp PageExplorer/wxPlasmaTextCtrl.cpp -o Tools/PageExplorer.exe

Misc/TypeMap.exe: Misc/TypeMap.cpp core/lib/libPlasma.dll
	$(CC) $(CFLAGS) -Lcore/lib/ -lPlasma -Icore Misc/TypeMap.cpp -o Misc/TypeMap.exe
clean:
	(cd core ; make clean)
	(cd Python ; make clean)

distclean:
	(cd core ; make distclean)
	(cd Python ; make distclean)
	rm -f Tools/PageConvert.exe
	rm -f Tools/PlasmaCrypt.exe
	rm -f Tools/PrpPack.exe
	rm -f Tools/PrcExtract.exe
	rm -f Tools/PageList.exe
	rm -f Tools/prcc.exe
	rm -f Tools/prcdc.exe
	rm -f Tools/Prp2Obj.exe
	rm -f Tools/PageExplorer.exe
	rm -f Misc/TypeMap.exe
