CXX = g++
CXXFLAGS += -fPIC -Wall -g -ansi -fno-rtti

PREFIX = /usr/local
BINDIR = bin

all:
	(cd core ; $(MAKE) -fMakefile.linux)
	(cd Python ; $(MAKE) -fMakefile.linux)
	($(MAKE) -fMakefile.linux $(BINDIR)/PageConvert)
	($(MAKE) -fMakefile.linux $(BINDIR)/PlasmaCrypt)
	($(MAKE) -fMakefile.linux $(BINDIR)/PrpPack)
	($(MAKE) -fMakefile.linux $(BINDIR)/PrcExtract)
	($(MAKE) -fMakefile.linux $(BINDIR)/PageList)
	($(MAKE) -fMakefile.linux $(BINDIR)/prcc)
	($(MAKE) -fMakefile.linux $(BINDIR)/prcdc)
	($(MAKE) -fMakefile.linux $(BINDIR)/Prp2Obj)
	($(MAKE) -fMakefile.linux $(BINDIR)/PyPack)
	($(MAKE) -fMakefile.linux $(BINDIR)/PageEditor)
	($(MAKE) -fMakefile.linux Misc/TypeMap)

$(BINDIR)/PageConvert: Tools/src/PageConvert.cpp $(BINDIR)/libPlasma.so
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PageConvert.cpp -o $@

$(BINDIR)/PlasmaCrypt: Tools/src/PlasmaCrypt.cpp $(BINDIR)/libPlasma.so
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PlasmaCrypt.cpp -o $@

$(BINDIR)/PrpPack: Tools/src/PrpPack.cpp $(BINDIR)/libPlasma.so
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PrpPack.cpp -o $@

$(BINDIR)/PrcExtract: Tools/src/PrcExtract.cpp $(BINDIR)/libPlasma.so
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PrcExtract.cpp -o $@

$(BINDIR)/PageList: Tools/src/PageList.cpp $(BINDIR)/libPlasma.so
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PageList.cpp -o $@

$(BINDIR)/prcc: Tools/src/prcc.cpp $(BINDIR)/libPlasma.so
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/prcc.cpp -o $@

$(BINDIR)/prcdc: Tools/src/prcdc.cpp $(BINDIR)/libPlasma.so
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/prcdc.cpp -o $@

$(BINDIR)/Prp2Obj: Tools/src/Prp2Obj.cpp $(BINDIR)/libPlasma.so
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/Prp2Obj.cpp -o $@

$(BINDIR)/PyPack: Tools/src/PyPack.cpp $(BINDIR)/libPlasma.so
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Tools/src/PyPack.cpp -o $@

$(BINDIR)/PageEditor: PageEditor/PageEditor.cpp PageEditor/ExplorerFrm.cpp PageEditor/CreateFrm.cpp PageEditor/CHexEditCtrl.cpp PageEditor/wxPlasmaTextCtrl.cpp PageEditor/PlasmaTreeItem.cpp $(BINDIR)/libPlasma.so
	$(CXX) $(CXXFLAGS) `wx-config --cxxflags --libs std,stc` -L$(BINDIR)/ -lPlasma -Icore PageEditor/PageEditor.cpp PageEditor/CreateFrm.cpp PageEditor/ExplorerFrm.cpp PageEditor/wxPlasmaTextCtrl.cpp PageEditor/CHexEditCtrl.cpp PageEditor/PlasmaTreeItem.cpp -o $@

Misc/TypeMap: Misc/TypeMap.cpp $(BINDIR)/libPlasma.so
	$(CXX) $(CXXFLAGS) -L$(BINDIR)/ -lPlasma -Icore Misc/TypeMap.cpp -o $@

install:
	(cd core ; $(MAKE) -fMakefile.linux install)
	(cd Python ; $(MAKE) -fMakefile.linux install)
	cp $(BINDIR)/PageConvert $(PREFIX)/bin/
	cp $(BINDIR)/PlasmaCrypt $(PREFIX)/bin/
	cp $(BINDIR)/PrpPack $(PREFIX)/bin/
	cp $(BINDIR)/PrcExtract $(PREFIX)/bin/
	cp $(BINDIR)/PageList $(PREFIX)/bin/
	cp $(BINDIR)/prcc $(PREFIX)/bin/
	cp $(BINDIR)/prcdc $(PREFIX)/bin/
	cp $(BINDIR)/Prp2Obj $(PREFIX)/bin/
	cp $(BINDIR)/PyPack $(PREFIX)/bin/
	cp $(BINDIR)/PageEditor $(PREFIX)/bin/
	chmod +x $(BINDIR)/eoaedit $(BINDIR)/uruedit
	cp $(BINDIR)/eoaedit $(BINDIR)/uruedit $(PREFIX)/bin/

uninstall:
	(cd core ; $(MAKE) -fMakefile.linux uninstall)
	(cd Python ; $(MAKE) -fMakefile.linux uninstall)
	rm -f $(PREFIX)/bin/PageConvert
	rm -f $(PREFIX)/bin/PlasmaCrypt
	rm -f $(PREFIX)/bin/PrpPack
	rm -f $(PREFIX)/bin/PrcExtract
	rm -f $(PREFIX)/bin/PageList
	rm -f $(PREFIX)/bin/prcc
	rm -f $(PREFIX)/bin/prcdc
	rm -f $(PREFIX)/bin/Prp2Obj
	rm -f $(PREFIX)/bin/PyPack
	rm -f $(PREFIX)/bin/PageEditor
	rm -f $(PREFIX)/bin/eoaedit
	rm -f $(PREFIX)/bin/uruedit

clean:
	(cd core ; $(MAKE) -fMakefile.linux clean)
	(cd Python ; $(MAKE) -fMakefile.linux clean)

distclean:
	(cd core ; $(MAKE) -fMakefile.linux distclean)
	(cd Python ; $(MAKE) -fMakefile.linux distclean)
	rm -f $(BINDIR)/PageConvert
	rm -f $(BINDIR)/PlasmaCrypt
	rm -f $(BINDIR)/PrpPack
	rm -f $(BINDIR)/PrcExtract
	rm -f $(BINDIR)/PageList
	rm -f $(BINDIR)/prcc
	rm -f $(BINDIR)/prcdc
	rm -f $(BINDIR)/Prp2Obj
	rm -f $(BINDIR)/PyPack
	rm -f $(BINDIR)/PageEditor
	rm -f Misc/TypeMap
