#! /bin/sh

#
# This is a simple script to copy component dirs into correct locations
# (and do some simple build stuff)
#
# AUTOGENERATED WITH wxcdist distscript/generate.py
#

if test "$1" = "--help"; then
  echo "If you run this script without arguments the necessary information will"
  echo "be asked. You can however supply your wxWidgets directory as the first"
  echo "argument and build-subdir (for instance: ./, build-debug, or buildgtk2)"
  echo "as the second one. Also, if you supply any arguments then quick install"
  echo "will be done, which means that the default contrib dir is assumed and"
  echo "library will not be automatically built."
  exit 0;
fi

echo "INSTALLING WXWIDGETS COMPONENT: propgrid 1.2.5"
if test ! -r "contrib/readme-propgrid.txt"; then
  # Try chmodding contents of contrib dir first
  chmod -R 755 contrib
  if test ! -r "contrib/readme-propgrid.txt"; then
    echo ".   contrib/readme-propgrid.txt does not exist or is unaccessible."
    echo ".   This script is probably being executed in wrong directory."
    echo "."
    echo ". install aborted"
    exit 1;
  fi
fi

# get current working dir
declare installcwd="`pwd`"

# try auto-running the script
if test ! "$1" = ""; then
  declare basewxdir="$1"
fi

# query base dir
if test "$1" = ""; then
  echo "Enter your wxWidgets base directory"
  read basewxdir
  if test "$basewxdir" = ""; then
    echo ". must give valid dir!"
    echo ". install aborted"
    exit 1;
  fi
fi

# let's convert relative dir to absolute
PT=`echo ${basewxdir} | grep '^/'`
if test ! "x$PT" != "x" ; then
  PT=`echo ${basewxdir} | grep '^~'`
  if test ! "x$PT" != "x" ; then
    declare basewxdir="`pwd`/$basewxdir"
  fi
fi

# it must exist
if test ! -r $basewxdir; then
  echo ". directory $basewxdir does not exist!"
  echo ". install aborted"
  exit 1;
fi
# it must be valid wxWidgets dir (check for project name in version.h)
LINE=`grep "wxWidgets" ${basewxdir}/include/wx/version.h`
if test ! "x$LINE" != "x" ; then
  # lets be nice and support wxWindows too
  LINE=`grep "wxWindows" ${basewxdir}/include/wx/version.h`
  if test ! "x$LINE" != "x" ; then
    echo ". directory $basewxdir is not wxWidgets directory!"
    echo ". install aborted"
    exit 1;
  fi
fi

echo ". selected base directory: $basewxdir"

# detect library version
echo ". detecting library version..."
declare libver=""
# test for 2.8.0
if test "$libver" = ""; then
  LINE=`grep "wxWidgets 2.8.0" ${basewxdir}/include/wx/version.h`
  if test "x$LINE" != "x" ; then
    declare libver="2.8.0"
  fi
fi

# test for 2.7.2
if test "$libver" = ""; then
  LINE=`grep "wxWidgets 2.7.2" ${basewxdir}/include/wx/version.h`
  if test "x$LINE" != "x" ; then
    declare libver="2.7.2"
  fi
fi

# test for 2.6.3
if test "$libver" = ""; then
  LINE=`grep "wxWidgets 2.6.3" ${basewxdir}/include/wx/version.h`
  if test "x$LINE" != "x" ; then
    declare libver="2.6.3"
  fi
fi

# test for 2.6.2
if test "$libver" = ""; then
  LINE=`grep "wxWidgets 2.6.2" ${basewxdir}/include/wx/version.h`
  if test "x$LINE" != "x" ; then
    declare libver="2.6.2"
  fi
fi

# test for 2.6.1
if test "$libver" = ""; then
  LINE=`grep "wxWidgets 2.6.1" ${basewxdir}/include/wx/version.h`
  if test "x$LINE" != "x" ; then
    declare libver="2.6.1"
  fi
fi

if test "$libver" = ""; then
  declare libver_supported="n"
  echo ".   officially supported version not detected"
  declare libver="2.8.0"
else
  declare libver_supported="y"
  echo ".   found: $libver"
fi

if test ! "$1" = ""; then
  declare subwxdir="contrib"
fi

# query sub dir
if test "$1" = ""; then
  echo "Enter sub-directory to install [contrib]"
  read subwxdir
  if test "$subwxdir" = ""; then
    declare subwxdir="contrib"
  fi
fi

echo ". selected sub-directory: $subwxdir"

# test sub dir
if test ! -r $basewxdir/$subwxdir; then
  echo "$basewxdir/$subwxdir does not exist. Create? [Y]"
  read msgres
  if test "$msgres" = "n"; then
    echo "Install aborted"
    exit 1;
  fi
  if test "$msgres" = "N"; then
    echo "Install aborted"
    exit 1;
  fi
fi

# test existing installation
if test "$1" = ""; then
  if test -r "$basewxdir/$subwxdir/build/propgrid"; then
    echo "Installation already exists. Overwrite [Y]?"
    read msgres
    if test "$msgres" = "n"; then
      echo "Install aborted"
      exit 1;
    fi
    if test "$msgres" = "N"; then
      echo "Install aborted"
      exit 1;
    fi
  fi
fi

# copy files
echo ". copying files"

cp -f contrib/CHANGES-propgrid.txt $basewxdir/$subwxdir/CHANGES-propgrid.txt
cp -f contrib/readme-propgrid.txt $basewxdir/$subwxdir/readme-propgrid.txt
cp -f contrib/index-propgrid.html $basewxdir/$subwxdir/index-propgrid.html
cp -f contrib/uninstall-propgrid.sh $basewxdir/$subwxdir/uninstall-propgrid.sh

mkdir -p $basewxdir/$subwxdir/src/propgrid
cp -f contrib/src/propgrid/advprops.cpp $basewxdir/$subwxdir/src/propgrid/advprops.cpp
cp -f contrib/src/propgrid/extras.cpp $basewxdir/$subwxdir/src/propgrid/extras.cpp
cp -f contrib/src/propgrid/manager.cpp $basewxdir/$subwxdir/src/propgrid/manager.cpp
cp -f contrib/src/propgrid/odcombo.cpp $basewxdir/$subwxdir/src/propgrid/odcombo.cpp
cp -f contrib/src/propgrid/propgrid.cpp $basewxdir/$subwxdir/src/propgrid/propgrid.cpp
cp -f contrib/src/propgrid/props.cpp $basewxdir/$subwxdir/src/propgrid/props.cpp
if test ! "$libver" = "2.8.0"; then
  cp -f contrib/src/propgrid/Makefile.$libver.in $basewxdir/$subwxdir/src/propgrid/Makefile.in
else
  if test "$libver_supported" = "y"; then
    cp -f contrib/src/propgrid/Makefile.in $basewxdir/$subwxdir/src/propgrid/Makefile.in
  fi
fi

mkdir -p $basewxdir/$subwxdir/build/propgrid
cp -f contrib/build/propgrid/propgrid.bkl $basewxdir/$subwxdir/build/propgrid/propgrid.bkl

mkdir -p $basewxdir/$subwxdir/samples/propgrid
cp -f contrib/samples/propgrid/propgridsample.cpp $basewxdir/$subwxdir/samples/propgrid/propgridsample.cpp
cp -f contrib/samples/propgrid/sampleprops.cpp $basewxdir/$subwxdir/samples/propgrid/sampleprops.cpp
cp -f contrib/samples/propgrid/propgridsample.h $basewxdir/$subwxdir/samples/propgrid/propgridsample.h
cp -f contrib/samples/propgrid/sampleprops.h $basewxdir/$subwxdir/samples/propgrid/sampleprops.h
cp -f contrib/samples/propgrid/propgridsample.bkl $basewxdir/$subwxdir/samples/propgrid/propgridsample.bkl
cp -f contrib/samples/propgrid/mondrian.xpm $basewxdir/$subwxdir/samples/propgrid/mondrian.xpm
cp -f contrib/samples/propgrid/mondrian.ico $basewxdir/$subwxdir/samples/propgrid/mondrian.ico
cp -f contrib/samples/propgrid/make.sh $basewxdir/$subwxdir/samples/propgrid/make.sh
cp -f contrib/samples/propgrid/make_clean.sh $basewxdir/$subwxdir/samples/propgrid/make_clean.sh
if test ! "$libver" = "2.8.0"; then
  cp -f contrib/samples/propgrid/Makefile.$libver.in $basewxdir/$subwxdir/samples/propgrid/Makefile.in
else
  if test "$libver_supported" = "y"; then
    cp -f contrib/samples/propgrid/Makefile.in $basewxdir/$subwxdir/samples/propgrid/Makefile.in
  fi
fi

mkdir -p $basewxdir/$subwxdir/docs/html/propgrid
cp -f contrib/docs/html/propgrid/annotated.htm $basewxdir/$subwxdir/docs/html/propgrid/annotated.htm
cp -f contrib/docs/html/propgrid/classes.htm $basewxdir/$subwxdir/docs/html/propgrid/classes.htm
cp -f contrib/docs/html/propgrid/classwxColourPropertyValue-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxColourPropertyValue-members.htm
cp -f contrib/docs/html/propgrid/classwxColourPropertyValue.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxColourPropertyValue.htm
cp -f contrib/docs/html/propgrid/classwxCustomPropertyClass-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxCustomPropertyClass-members.htm
cp -f contrib/docs/html/propgrid/classwxCustomPropertyClass.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxCustomPropertyClass.htm
cp -f contrib/docs/html/propgrid/classwxCustomPropertyClass.png $basewxdir/$subwxdir/docs/html/propgrid/classwxCustomPropertyClass.png
cp -f contrib/docs/html/propgrid/classwxParentPropertyClass-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxParentPropertyClass-members.htm
cp -f contrib/docs/html/propgrid/classwxParentPropertyClass.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxParentPropertyClass.htm
cp -f contrib/docs/html/propgrid/classwxParentPropertyClass.png $basewxdir/$subwxdir/docs/html/propgrid/classwxParentPropertyClass.png
cp -f contrib/docs/html/propgrid/classwxPGChoices-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGChoices-members.htm
cp -f contrib/docs/html/propgrid/classwxPGChoices.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGChoices.htm
cp -f contrib/docs/html/propgrid/classwxPGEditor-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGEditor-members.htm
cp -f contrib/docs/html/propgrid/classwxPGEditor.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGEditor.htm
cp -f contrib/docs/html/propgrid/classwxPGEditor.png $basewxdir/$subwxdir/docs/html/propgrid/classwxPGEditor.png
cp -f contrib/docs/html/propgrid/classwxPGId-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGId-members.htm
cp -f contrib/docs/html/propgrid/classwxPGId.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGId.htm
cp -f contrib/docs/html/propgrid/classwxPGInDialogValidator-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGInDialogValidator-members.htm
cp -f contrib/docs/html/propgrid/classwxPGInDialogValidator.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGInDialogValidator.htm
cp -f contrib/docs/html/propgrid/classwxPGPaintData-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGPaintData-members.htm
cp -f contrib/docs/html/propgrid/classwxPGProperty-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGProperty-members.htm
cp -f contrib/docs/html/propgrid/classwxPGProperty.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGProperty.htm
cp -f contrib/docs/html/propgrid/classwxPGProperty.png $basewxdir/$subwxdir/docs/html/propgrid/classwxPGProperty.png
cp -f contrib/docs/html/propgrid/classwxPGPropertyClassInfo-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGPropertyClassInfo-members.htm
cp -f contrib/docs/html/propgrid/classwxPGPropertyDataExt-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGPropertyDataExt-members.htm
cp -f contrib/docs/html/propgrid/classwxPGPropertyDataExt.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGPropertyDataExt.htm
cp -f contrib/docs/html/propgrid/classwxPGPropertyWithChildren-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGPropertyWithChildren-members.htm
cp -f contrib/docs/html/propgrid/classwxPGPropertyWithChildren.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGPropertyWithChildren.htm
cp -f contrib/docs/html/propgrid/classwxPGPropertyWithChildren.png $basewxdir/$subwxdir/docs/html/propgrid/classwxPGPropertyWithChildren.png
cp -f contrib/docs/html/propgrid/classwxPGRootPropertyClass-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGRootPropertyClass-members.htm
cp -f contrib/docs/html/propgrid/classwxPGRootPropertyClass.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGRootPropertyClass.htm
cp -f contrib/docs/html/propgrid/classwxPGRootPropertyClass.png $basewxdir/$subwxdir/docs/html/propgrid/classwxPGRootPropertyClass.png
cp -f contrib/docs/html/propgrid/classwxPGValueType-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGValueType-members.htm
cp -f contrib/docs/html/propgrid/classwxPGValueType.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGValueType.htm
cp -f contrib/docs/html/propgrid/classwxPGVariantDataWxObj-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGVariantDataWxObj-members.htm
cp -f contrib/docs/html/propgrid/classwxPGVariantDataWxObj.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPGVariantDataWxObj.htm
cp -f contrib/docs/html/propgrid/classwxPropertyCategoryClass-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyCategoryClass-members.htm
cp -f contrib/docs/html/propgrid/classwxPropertyCategoryClass.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyCategoryClass.htm
cp -f contrib/docs/html/propgrid/classwxPropertyCategoryClass.png $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyCategoryClass.png
cp -f contrib/docs/html/propgrid/classwxPropertyContainerMethods-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyContainerMethods-members.htm
cp -f contrib/docs/html/propgrid/classwxPropertyContainerMethods.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyContainerMethods.htm
cp -f contrib/docs/html/propgrid/classwxPropertyContainerMethods.png $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyContainerMethods.png
cp -f contrib/docs/html/propgrid/classwxPropertyGrid-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGrid-members.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGrid.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGrid.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGrid.png $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGrid.png
cp -f contrib/docs/html/propgrid/classwxPropertyGridEvent-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridEvent-members.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGridEvent.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridEvent.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGridManager-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridManager-members.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGridManager.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridManager.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGridManager.png $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridManager.png
cp -f contrib/docs/html/propgrid/classwxPropertyGridPage-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridPage-members.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGridPage.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridPage.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGridPage.png $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridPage.png
cp -f contrib/docs/html/propgrid/classwxPropertyGridPopulator-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridPopulator-members.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGridPopulator.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridPopulator.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGridState-members.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridState-members.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGridState.htm $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridState.htm
cp -f contrib/docs/html/propgrid/classwxPropertyGridState.png $basewxdir/$subwxdir/docs/html/propgrid/classwxPropertyGridState.png
cp -f contrib/docs/html/propgrid/doxygen.css $basewxdir/$subwxdir/docs/html/propgrid/doxygen.css
cp -f contrib/docs/html/propgrid/doxygen.png $basewxdir/$subwxdir/docs/html/propgrid/doxygen.png
cp -f contrib/docs/html/propgrid/functions.htm $basewxdir/$subwxdir/docs/html/propgrid/functions.htm
cp -f contrib/docs/html/propgrid/functions_0x62.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x62.htm
cp -f contrib/docs/html/propgrid/functions_0x63.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x63.htm
cp -f contrib/docs/html/propgrid/functions_0x64.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x64.htm
cp -f contrib/docs/html/propgrid/functions_0x65.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x65.htm
cp -f contrib/docs/html/propgrid/functions_0x66.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x66.htm
cp -f contrib/docs/html/propgrid/functions_0x67.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x67.htm
cp -f contrib/docs/html/propgrid/functions_0x68.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x68.htm
cp -f contrib/docs/html/propgrid/functions_0x69.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x69.htm
cp -f contrib/docs/html/propgrid/functions_0x6c.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x6c.htm
cp -f contrib/docs/html/propgrid/functions_0x6d.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x6d.htm
cp -f contrib/docs/html/propgrid/functions_0x6f.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x6f.htm
cp -f contrib/docs/html/propgrid/functions_0x70.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x70.htm
cp -f contrib/docs/html/propgrid/functions_0x72.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x72.htm
cp -f contrib/docs/html/propgrid/functions_0x73.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x73.htm
cp -f contrib/docs/html/propgrid/functions_0x74.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x74.htm
cp -f contrib/docs/html/propgrid/functions_0x75.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x75.htm
cp -f contrib/docs/html/propgrid/functions_0x77.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x77.htm
cp -f contrib/docs/html/propgrid/functions_0x7e.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_0x7e.htm
cp -f contrib/docs/html/propgrid/functions_func.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func.htm
cp -f contrib/docs/html/propgrid/functions_func_0x62.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x62.htm
cp -f contrib/docs/html/propgrid/functions_func_0x63.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x63.htm
cp -f contrib/docs/html/propgrid/functions_func_0x64.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x64.htm
cp -f contrib/docs/html/propgrid/functions_func_0x65.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x65.htm
cp -f contrib/docs/html/propgrid/functions_func_0x66.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x66.htm
cp -f contrib/docs/html/propgrid/functions_func_0x67.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x67.htm
cp -f contrib/docs/html/propgrid/functions_func_0x68.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x68.htm
cp -f contrib/docs/html/propgrid/functions_func_0x69.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x69.htm
cp -f contrib/docs/html/propgrid/functions_func_0x6c.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x6c.htm
cp -f contrib/docs/html/propgrid/functions_func_0x6f.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x6f.htm
cp -f contrib/docs/html/propgrid/functions_func_0x70.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x70.htm
cp -f contrib/docs/html/propgrid/functions_func_0x72.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x72.htm
cp -f contrib/docs/html/propgrid/functions_func_0x73.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x73.htm
cp -f contrib/docs/html/propgrid/functions_func_0x74.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x74.htm
cp -f contrib/docs/html/propgrid/functions_func_0x75.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x75.htm
cp -f contrib/docs/html/propgrid/functions_func_0x77.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x77.htm
cp -f contrib/docs/html/propgrid/functions_func_0x7e.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_func_0x7e.htm
cp -f contrib/docs/html/propgrid/functions_vars.htm $basewxdir/$subwxdir/docs/html/propgrid/functions_vars.htm
cp -f contrib/docs/html/propgrid/group__attrids.htm $basewxdir/$subwxdir/docs/html/propgrid/group__attrids.htm
cp -f contrib/docs/html/propgrid/group__miscellaneous.htm $basewxdir/$subwxdir/docs/html/propgrid/group__miscellaneous.htm
cp -f contrib/docs/html/propgrid/group__propflags.htm $basewxdir/$subwxdir/docs/html/propgrid/group__propflags.htm
cp -f contrib/docs/html/propgrid/group__wndflags.htm $basewxdir/$subwxdir/docs/html/propgrid/group__wndflags.htm
cp -f contrib/docs/html/propgrid/hierarchy.htm $basewxdir/$subwxdir/docs/html/propgrid/hierarchy.htm
cp -f contrib/docs/html/propgrid/index.htm $basewxdir/$subwxdir/docs/html/propgrid/index.htm
cp -f contrib/docs/html/propgrid/modules.htm $basewxdir/$subwxdir/docs/html/propgrid/modules.htm
cp -f contrib/docs/html/propgrid/search.idx $basewxdir/$subwxdir/docs/html/propgrid/search.idx
cp -f contrib/docs/html/propgrid/search.php $basewxdir/$subwxdir/docs/html/propgrid/search.php
cp -f contrib/docs/html/propgrid/structwxPGPaintData-members.htm $basewxdir/$subwxdir/docs/html/propgrid/structwxPGPaintData-members.htm
cp -f contrib/docs/html/propgrid/structwxPGPaintData.htm $basewxdir/$subwxdir/docs/html/propgrid/structwxPGPaintData.htm
cp -f contrib/docs/html/propgrid/structwxPGPropertyClassInfo-members.htm $basewxdir/$subwxdir/docs/html/propgrid/structwxPGPropertyClassInfo-members.htm
cp -f contrib/docs/html/propgrid/structwxPGPropertyClassInfo.htm $basewxdir/$subwxdir/docs/html/propgrid/structwxPGPropertyClassInfo.htm
cp -f contrib/docs/html/propgrid/tabs.css $basewxdir/$subwxdir/docs/html/propgrid/tabs.css
cp -f contrib/docs/html/propgrid/tab_b.gif $basewxdir/$subwxdir/docs/html/propgrid/tab_b.gif
cp -f contrib/docs/html/propgrid/tab_l.gif $basewxdir/$subwxdir/docs/html/propgrid/tab_l.gif
cp -f contrib/docs/html/propgrid/tab_r.gif $basewxdir/$subwxdir/docs/html/propgrid/tab_r.gif

mkdir -p $basewxdir/$subwxdir/include/wx/propgrid
cp -f contrib/include/wx/propgrid/advprops.h $basewxdir/$subwxdir/include/wx/propgrid/advprops.h
cp -f contrib/include/wx/propgrid/extras.h $basewxdir/$subwxdir/include/wx/propgrid/extras.h
cp -f contrib/include/wx/propgrid/manager.h $basewxdir/$subwxdir/include/wx/propgrid/manager.h
cp -f contrib/include/wx/propgrid/odcombo.h $basewxdir/$subwxdir/include/wx/propgrid/odcombo.h
cp -f contrib/include/wx/propgrid/pg_dox_mainpage.h $basewxdir/$subwxdir/include/wx/propgrid/pg_dox_mainpage.h
cp -f contrib/include/wx/propgrid/propdev.h $basewxdir/$subwxdir/include/wx/propgrid/propdev.h
cp -f contrib/include/wx/propgrid/propgrid.h $basewxdir/$subwxdir/include/wx/propgrid/propgrid.h
cp -f contrib/include/wx/propgrid/Doxyfile $basewxdir/$subwxdir/include/wx/propgrid/Doxyfile
cp -f contrib/include/wx/propgrid/propgrid.doxygen $basewxdir/$subwxdir/include/wx/propgrid/propgrid.doxygen

# run bakefile if neeeded
if test "$libver_supported" = "n"; then
  echo ". trying to run bakefile"
  echo ".   NOTE: If bakefile is not found or fails to execute, it is"
  echo ".         unlikely that makefiles will work out of the box."

  cd $basewxdir/build/bakefiles
  bakefile_gen --desc Bakefiles.bkgen -fautoconf -b../../contrib/build/propgrid/propgrid.bkl,../../contrib/samples/propgrid/propgridsample.bkl
  cd $installcwd

fi

# get subdir from command-line
if test ! "$2" = ""; then
  declare subbuilddir="$2"
fi

# Ask subdir, if not from command line
if test "$2" = ""; then
  echo "Enter build directory (For example, 'buildgtk2' or 'build-debug'."
  echo "If you simply have run configure in base wxWidgets dir, just press"
  echo "enter now)"
  read subbuilddir
fi

# test sub dir
if test ! -r $basewxdir/$subbuilddir; then
  echo "Build directory doesn't exist, so nothing more can be done!"
  exit 1;
fi

# regenerate makefiles
if test "$subbuilddir" = ""; then
  cd $basewxdir
else
  cd $basewxdir/$subbuilddir
fi

$basewxdir/regen $subwxdir/src/propgrid/Makefile $subwxdir/samples/propgrid/Makefile

# copy helper scripts make.sh and make_clean.sh
cp -f $basewxdir/$subwxdir/samples/propgrid/*.sh $basewxdir/$subbuilddir/$subwxdir/samples/propgrid

# exit now if this was quick install
if test ! "$1" = ""; then
  echo ". quick install complete"
  exit 0;
fi

echo ". install complete"

# show extra information
if test ! "$subwxdir" = "contrib"; then
    echo ""
    echo "Since you installed in another directory than contrib, running the"
    echo "configure script will not generate makefiles unless you change line"
    echo ""
    echo "    SUBDIRS="samples demos utils contrib""
    echo ""
    echo "into"
    echo ""
    echo "    SUBDIRS="samples demos utils contrib $subwxdir""
    echo ""
    echo "Inorder to build the library and sample, and then run the sample, do the following:"
    echo ""
    echo "    cd <your_wxwidgets_library_dir>"
    echo "    ./configure or ../configure depending are you in wxWidgets base dir or a subdir"
    echo "    cd $subwxdir/src/propgrid"
    echo "    make"
    echo "    cd ../../samples/propgrid"
    echo "    make"
    echo "    ./propgridsample"
    echo ""
    exit 0;
fi

# ask if user wants to build the lib
echo "Do want to build the library and sample, and then run the sample [Y]?"
read msgres
if test "$msgres" = "n"; then
  echo ". wxPropertyGrid Makefile.in is in $basewxdir/$subwxdir/src/propgrid"
  echo ". wxPropertyGrid Sample Makefile.in is in $basewxdir/$subwxdir/samples/propgrid"
  echo ". build like any other single wxWidgets contrib (running make in contrib"
  echo "  probably doesn't work out-of-the-box. For details, see:"
  echo "      contrib/readme-propgrid.txt"
  exit 0;
fi
if test "$msgres" = "N"; then
  echo ". wxPropertyGrid Makefile.in is in $basewxdir/$subwxdir/src/propgrid"
  echo ". wxPropertyGrid Sample Makefile.in is in $basewxdir/$subwxdir/samples/propgrid"
  echo ". build like any other single wxWidgets contrib (calling make in contrib probably"
  echo "  doesn't work out-of-the-box - see contrib/readme-propgrid.txt for details)"
  exit 0;
fi

#echo "Enter library directory (For example, 'buildgtk2' or 'build-debug'."
#echo "If you simply have run configure in base wxWidgets dir, just enter an empty string )"
#read subbuilddir

# test sub dir
#if test ! -r $basewxdir/$subbuilddir; then
#  echo "Directory doesn't exist, so nothing can be done!"
#  exit 0;
#fi

# make
cd $subwxdir/src/propgrid
make
cd ../../samples/propgrid
make
./propgridsample
