CXX = g++
CXXFLAGS = -I../core -fPIC -Wall -g -ansi -fno-rtti `python-config --cflags` -arch ppc -arch i386 -DMACOSX
CXXLINK  = -L../core/lib -lPlasma `python-config --libs` -arch ppc -arch i386

OBJDIR=out/

PYOBJ=\
	$(OBJDIR)Module.o \
	$(OBJDIR)pyDebug.o \
	$(OBJDIR)pyAffineParts.o \
	$(OBJDIR)pyMatrix33.o \
	$(OBJDIR)pyMatrix44.o \
	$(OBJDIR)pyPlane3.o \
	$(OBJDIR)pyQuat.o \
	$(OBJDIR)pyVector3.o \
	$(OBJDIR)pyCreatable.o \
	$(OBJDIR)pyCreatableStub.o \
	$(OBJDIR)pyAnimTimeConvert.o \
	$(OBJDIR)pyATCEaseCurve.o \
	$(OBJDIR)pyCompoundController.o \
	$(OBJDIR)pyCompoundPosController.o \
	$(OBJDIR)pyCompoundRotController.o \
	$(OBJDIR)pyCompressedQuatKey32.o \
	$(OBJDIR)pyCompressedQuatKey64.o \
	$(OBJDIR)pyConstAccelEaseCurve.o \
	$(OBJDIR)pyController.o \
	$(OBJDIR)pyEaseController.o \
	$(OBJDIR)pyG3DSMaxKeyFrame.o \
	$(OBJDIR)pyKeyFrame.o \
	$(OBJDIR)pyLeafController.o \
	$(OBJDIR)pyMatrix33Controller.o \
	$(OBJDIR)pyMatrix33Key.o \
	$(OBJDIR)pyMatrix44Controller.o \
	$(OBJDIR)pyMatrix44Key.o \
	$(OBJDIR)pyPoint3Controller.o \
	$(OBJDIR)pyPoint3Key.o \
	$(OBJDIR)pyPosController.o \
	$(OBJDIR)pyQuatController.o \
	$(OBJDIR)pyQuatKey.o \
	$(OBJDIR)pyRotController.o \
	$(OBJDIR)pyScalarController.o \
	$(OBJDIR)pyScalarKey.o \
	$(OBJDIR)pyScaleController.o \
	$(OBJDIR)pyScaleKey.o \
	$(OBJDIR)pyScaleValueController.o \
	$(OBJDIR)pySimplePosController.o \
	$(OBJDIR)pySimpleRotController.o \
	$(OBJDIR)pySimpleScaleController.o \
	$(OBJDIR)pySplineEaseCurve.o \
	$(OBJDIR)pyTMController.o \
	$(OBJDIR)pyViewFaceModifier.o \
	$(OBJDIR)pySceneNode.o \
	$(OBJDIR)pySoundBuffer.o \
	$(OBJDIR)pyWAVHeader.o \
	$(OBJDIR)pyCluster.o \
	$(OBJDIR)pyClusterGroup.o \
	$(OBJDIR)pyDISpanIndex.o \
	$(OBJDIR)pyDrawable.o \
	$(OBJDIR)pyDrawableSpans.o \
	$(OBJDIR)pyGBufferCell.o \
	$(OBJDIR)pyGBufferGroup.o \
	$(OBJDIR)pyGBufferTriangle.o \
	$(OBJDIR)pyGBufferVertex.o \
	$(OBJDIR)pyIcicle.o \
	$(OBJDIR)pyLODDist.o \
	$(OBJDIR)pyParticleSpan.o \
	$(OBJDIR)pySpaceTree.o \
	$(OBJDIR)pySpaceTreeNode.o \
	$(OBJDIR)pySpan.o \
	$(OBJDIR)pySpanEncoding.o \
	$(OBJDIR)pySpanInstance.o \
	$(OBJDIR)pySpanTemplate.o \
	$(OBJDIR)pySpanTemplateVertex.o \
	$(OBJDIR)pyVertexSpan.o \
	$(OBJDIR)pyKey.o \
	$(OBJDIR)pyKeyedObject.o \
	$(OBJDIR)pyLocation.o \
	$(OBJDIR)pyDirectionalLightInfo.o \
	$(OBJDIR)pyLightInfo.o \
	$(OBJDIR)pyLimitedDirLightInfo.o \
	$(OBJDIR)pyOmniLightInfo.o \
	$(OBJDIR)pySpotLightInfo.o \
	$(OBJDIR)pyEventCallbackMsg.o \
	$(OBJDIR)pyMessage.o \
	$(OBJDIR)pyRenderLevel.o \
	$(OBJDIR)pyModifier.o \
	$(OBJDIR)pyMultiModifier.o \
	$(OBJDIR)pyOneShotMod.o \
	$(OBJDIR)pyPythonFileMod.o \
	$(OBJDIR)pyPythonParameter.o \
	$(OBJDIR)pyResponderEnableMsg.o \
	$(OBJDIR)pyResponderModifier.o \
	$(OBJDIR)pyResponderModifier_Cmd.o \
	$(OBJDIR)pyResponderModifier_State.o \
	$(OBJDIR)pySingleModifier.o \
	$(OBJDIR)pyAudioInterface.o \
	$(OBJDIR)pyCoordinateInterface.o \
	$(OBJDIR)pyDrawInterface.o \
	$(OBJDIR)pyObjInterface.o \
	$(OBJDIR)pySceneObject.o \
	$(OBJDIR)pySimulationInterface.o \
	$(OBJDIR)pySynchedObject.o \
	$(OBJDIR)pyGenericPhysical.o \
	$(OBJDIR)pyPhysical.o \
	$(OBJDIR)pySimDefs.o \
	$(OBJDIR)pyBounds.o \
	$(OBJDIR)pyBounds3.o \
	$(OBJDIR)pyBounds3Ext.o \
	$(OBJDIR)pyBoundsOriented.o \
	$(OBJDIR)pyBitmap.o \
	$(OBJDIR)pyGMaterial.o \
	$(OBJDIR)pyGMatState.o \
	$(OBJDIR)pyLayer.o \
	$(OBJDIR)pyLayerAnimation.o \
	$(OBJDIR)pyLayerAnimationBase.o \
	$(OBJDIR)pyLayerAVI.o \
	$(OBJDIR)pyLayerBink.o \
	$(OBJDIR)pyLayerDepth.o \
	$(OBJDIR)pyLayerInterface.o \
	$(OBJDIR)pyLayerLinkAnimation.o \
	$(OBJDIR)pyLayerMovie.o \
	$(OBJDIR)pyLayerSDLAnimation.o \
	$(OBJDIR)pyMipmap.o \
	$(OBJDIR)pyShader.o \
	$(OBJDIR)pyShaderConst.o \
	$(OBJDIR)pyAgeInfo.o \
	$(OBJDIR)pyFactory.o \
	$(OBJDIR)pyResManager.o \
	$(OBJDIR)pyPageInfo.o \
	$(OBJDIR)pyEncryptedStream.o \
	$(OBJDIR)pyFileStream.o \
	$(OBJDIR)pyStream.o \
	$(OBJDIR)pyColor32.o \
	$(OBJDIR)pyColorRGBA.o \
	$(OBJDIR)pyBitVector.o

PYLIB=PyPlasma.so

all: $(PYLIB)

$(PYLIB): $(PYOBJ)
	$(CXX) $(CXXFLAGS) $(PYOBJ) $(CXXLINK) -dynamiclib -o $(PYLIB)

clean:
	rm -f $(PYOBJ)

distclean:
	rm -f $(PYLIB)

$(OBJDIR)Module.o: Module.cpp
	$(CXX) $(CXXFLAGS) -c Module.cpp -o $(OBJDIR)Module.o

$(OBJDIR)pyDebug.o: Debug/pyDebug.cpp
	$(CXX) $(CXXFLAGS) -c Debug/pyDebug.cpp -o $(OBJDIR)pyDebug.o

$(OBJDIR)pyAffineParts.o: Math/pyAffineParts.cpp
	$(CXX) $(CXXFLAGS) -c Math/pyAffineParts.cpp -o $(OBJDIR)pyAffineParts.o

$(OBJDIR)pyMatrix33.o: Math/pyMatrix33.cpp
	$(CXX) $(CXXFLAGS) -c Math/pyMatrix33.cpp -o $(OBJDIR)pyMatrix33.o

$(OBJDIR)pyMatrix44.o: Math/pyMatrix44.cpp
	$(CXX) $(CXXFLAGS) -c Math/pyMatrix44.cpp -o $(OBJDIR)pyMatrix44.o

$(OBJDIR)pyPlane3.o: Math/pyPlane3.cpp
	$(CXX) $(CXXFLAGS) -c Math/pyPlane3.cpp -o $(OBJDIR)pyPlane3.o

$(OBJDIR)pyQuat.o: Math/pyQuat.cpp
	$(CXX) $(CXXFLAGS) -c Math/pyQuat.cpp -o $(OBJDIR)pyQuat.o

$(OBJDIR)pyVector3.o: Math/pyVector3.cpp
	$(CXX) $(CXXFLAGS) -c Math/pyVector3.cpp -o $(OBJDIR)pyVector3.o

$(OBJDIR)pyCreatable.o: PRP/pyCreatable.cpp
	$(CXX) $(CXXFLAGS) -c PRP/pyCreatable.cpp -o $(OBJDIR)pyCreatable.o

$(OBJDIR)pyCreatableStub.o: PRP/pyCreatableStub.cpp
	$(CXX) $(CXXFLAGS) -c PRP/pyCreatableStub.cpp -o $(OBJDIR)pyCreatableStub.o

$(OBJDIR)pySceneNode.o: PRP/pySceneNode.cpp
	$(CXX) $(CXXFLAGS) -c PRP/pySceneNode.cpp -o $(OBJDIR)pySceneNode.o

$(OBJDIR)pyAnimTimeConvert.o: PRP/Animation/pyAnimTimeConvert.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyAnimTimeConvert.cpp -o $(OBJDIR)pyAnimTimeConvert.o

$(OBJDIR)pyATCEaseCurve.o: PRP/Animation/pyATCEaseCurve.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyATCEaseCurve.cpp -o $(OBJDIR)pyATCEaseCurve.o

$(OBJDIR)pyCompoundController.o: PRP/Animation/pyCompoundController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyCompoundController.cpp -o $(OBJDIR)pyCompoundController.o

$(OBJDIR)pyCompoundPosController.o: PRP/Animation/pyCompoundPosController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyCompoundPosController.cpp -o $(OBJDIR)pyCompoundPosController.o

$(OBJDIR)pyCompoundRotController.o: PRP/Animation/pyCompoundRotController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyCompoundRotController.cpp -o $(OBJDIR)pyCompoundRotController.o

$(OBJDIR)pyCompressedQuatKey32.o: PRP/Animation/pyCompressedQuatKey32.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyCompressedQuatKey32.cpp -o $(OBJDIR)pyCompressedQuatKey32.o

$(OBJDIR)pyCompressedQuatKey64.o: PRP/Animation/pyCompressedQuatKey64.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyCompressedQuatKey64.cpp -o $(OBJDIR)pyCompressedQuatKey64.o

$(OBJDIR)pyConstAccelEaseCurve.o: PRP/Animation/pyConstAccelEaseCurve.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyConstAccelEaseCurve.cpp -o $(OBJDIR)pyConstAccelEaseCurve.o

$(OBJDIR)pyController.o: PRP/Animation/pyController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyController.cpp -o $(OBJDIR)pyController.o

$(OBJDIR)pyEaseController.o: PRP/Animation/pyEaseController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyEaseController.cpp -o $(OBJDIR)pyEaseController.o

$(OBJDIR)pyG3DSMaxKeyFrame.o: PRP/Animation/pyG3DSMaxKeyFrame.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyG3DSMaxKeyFrame.cpp -o $(OBJDIR)pyG3DSMaxKeyFrame.o

$(OBJDIR)pyKeyFrame.o: PRP/Animation/pyKeyFrame.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyKeyFrame.cpp -o $(OBJDIR)pyKeyFrame.o

$(OBJDIR)pyLeafController.o: PRP/Animation/pyLeafController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyLeafController.cpp -o $(OBJDIR)pyLeafController.o

$(OBJDIR)pyMatrix33Controller.o: PRP/Animation/pyMatrix33Controller.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyMatrix33Controller.cpp -o $(OBJDIR)pyMatrix33Controller.o

$(OBJDIR)pyMatrix33Key.o: PRP/Animation/pyMatrix33Key.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyMatrix33Key.cpp -o $(OBJDIR)pyMatrix33Key.o

$(OBJDIR)pyMatrix44Controller.o: PRP/Animation/pyMatrix44Controller.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyMatrix44Controller.cpp -o $(OBJDIR)pyMatrix44Controller.o

$(OBJDIR)pyMatrix44Key.o: PRP/Animation/pyMatrix44Key.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyMatrix44Key.cpp -o $(OBJDIR)pyMatrix44Key.o

$(OBJDIR)pyPoint3Controller.o: PRP/Animation/pyPoint3Controller.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyPoint3Controller.cpp -o $(OBJDIR)pyPoint3Controller.o

$(OBJDIR)pyPoint3Key.o: PRP/Animation/pyPoint3Key.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyPoint3Key.cpp -o $(OBJDIR)pyPoint3Key.o

$(OBJDIR)pyPosController.o: PRP/Animation/pyPosController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyPosController.cpp -o $(OBJDIR)pyPosController.o

$(OBJDIR)pyQuatController.o: PRP/Animation/pyQuatController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyQuatController.cpp -o $(OBJDIR)pyQuatController.o

$(OBJDIR)pyQuatKey.o: PRP/Animation/pyQuatKey.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyQuatKey.cpp -o $(OBJDIR)pyQuatKey.o

$(OBJDIR)pyRotController.o: PRP/Animation/pyRotController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyRotController.cpp -o $(OBJDIR)pyRotController.o

$(OBJDIR)pyScalarController.o: PRP/Animation/pyScalarController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyScalarController.cpp -o $(OBJDIR)pyScalarController.o

$(OBJDIR)pyScalarKey.o: PRP/Animation/pyScalarKey.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyScalarKey.cpp -o $(OBJDIR)pyScalarKey.o

$(OBJDIR)pyScaleController.o: PRP/Animation/pyScaleController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyScaleController.cpp -o $(OBJDIR)pyScaleController.o

$(OBJDIR)pyScaleKey.o: PRP/Animation/pyScaleKey.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyScaleKey.cpp -o $(OBJDIR)pyScaleKey.o

$(OBJDIR)pyScaleValueController.o: PRP/Animation/pyScaleValueController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyScaleValueController.cpp -o $(OBJDIR)pyScaleValueController.o

$(OBJDIR)pySimplePosController.o: PRP/Animation/pySimplePosController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pySimplePosController.cpp -o $(OBJDIR)pySimplePosController.o

$(OBJDIR)pySimpleRotController.o: PRP/Animation/pySimpleRotController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pySimpleRotController.cpp -o $(OBJDIR)pySimpleRotController.o

$(OBJDIR)pySimpleScaleController.o: PRP/Animation/pySimpleScaleController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pySimpleScaleController.cpp -o $(OBJDIR)pySimpleScaleController.o

$(OBJDIR)pySplineEaseCurve.o: PRP/Animation/pySplineEaseCurve.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pySplineEaseCurve.cpp -o $(OBJDIR)pySplineEaseCurve.o

$(OBJDIR)pyTMController.o: PRP/Animation/pyTMController.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyTMController.cpp -o $(OBJDIR)pyTMController.o

$(OBJDIR)pyViewFaceModifier.o: PRP/Animation/pyViewFaceModifier.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Animation/pyViewFaceModifier.cpp -o $(OBJDIR)pyViewFaceModifier.o

$(OBJDIR)pySoundBuffer.o: PRP/Audio/pySoundBuffer.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Audio/pySoundBuffer.cpp -o $(OBJDIR)pySoundBuffer.o

$(OBJDIR)pyWAVHeader.o: PRP/Audio/pyWAVHeader.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Audio/pyWAVHeader.cpp -o $(OBJDIR)pyWAVHeader.o

$(OBJDIR)pyCluster.o: PRP/Geometry/pyCluster.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyCluster.cpp -o $(OBJDIR)pyCluster.o

$(OBJDIR)pyClusterGroup.o: PRP/Geometry/pyClusterGroup.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyClusterGroup.cpp -o $(OBJDIR)pyClusterGroup.o

$(OBJDIR)pyDISpanIndex.o: PRP/Geometry/pyDISpanIndex.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyDISpanIndex.cpp -o $(OBJDIR)pyDISpanIndex.o

$(OBJDIR)pyDrawable.o: PRP/Geometry/pyDrawable.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyDrawable.cpp -o $(OBJDIR)pyDrawable.o

$(OBJDIR)pyDrawableSpans.o: PRP/Geometry/pyDrawableSpans.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyDrawableSpans.cpp -o $(OBJDIR)pyDrawableSpans.o

$(OBJDIR)pyGBufferCell.o: PRP/Geometry/pyGBufferCell.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyGBufferCell.cpp -o $(OBJDIR)pyGBufferCell.o

$(OBJDIR)pyGBufferGroup.o: PRP/Geometry/pyGBufferGroup.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyGBufferGroup.cpp -o $(OBJDIR)pyGBufferGroup.o

$(OBJDIR)pyGBufferTriangle.o: PRP/Geometry/pyGBufferTriangle.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyGBufferTriangle.cpp -o $(OBJDIR)pyGBufferTriangle.o

$(OBJDIR)pyGBufferVertex.o: PRP/Geometry/pyGBufferVertex.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyGBufferVertex.cpp -o $(OBJDIR)pyGBufferVertex.o

$(OBJDIR)pyIcicle.o: PRP/Geometry/pyIcicle.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyIcicle.cpp -o $(OBJDIR)pyIcicle.o

$(OBJDIR)pyLODDist.o: PRP/Geometry/pyLODDist.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyLODDist.cpp -o $(OBJDIR)pyLODDist.o

$(OBJDIR)pyParticleSpan.o: PRP/Geometry/pyParticleSpan.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyParticleSpan.cpp -o $(OBJDIR)pyParticleSpan.o

$(OBJDIR)pySpaceTree.o: PRP/Geometry/pySpaceTree.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pySpaceTree.cpp -o $(OBJDIR)pySpaceTree.o

$(OBJDIR)pySpaceTreeNode.o: PRP/Geometry/pySpaceTreeNode.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pySpaceTreeNode.cpp -o $(OBJDIR)pySpaceTreeNode.o

$(OBJDIR)pySpan.o: PRP/Geometry/pySpan.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pySpan.cpp -o $(OBJDIR)pySpan.o

$(OBJDIR)pySpanEncoding.o: PRP/Geometry/pySpanEncoding.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pySpanEncoding.cpp -o $(OBJDIR)pySpanEncoding.o

$(OBJDIR)pySpanInstance.o: PRP/Geometry/pySpanInstance.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pySpanInstance.cpp -o $(OBJDIR)pySpanInstance.o

$(OBJDIR)pySpanTemplate.o: PRP/Geometry/pySpanTemplate.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pySpanTemplate.cpp -o $(OBJDIR)pySpanTemplate.o

$(OBJDIR)pySpanTemplateVertex.o: PRP/Geometry/pySpanTemplateVertex.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pySpanTemplateVertex.cpp -o $(OBJDIR)pySpanTemplateVertex.o

$(OBJDIR)pyVertexSpan.o: PRP/Geometry/pyVertexSpan.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Geometry/pyVertexSpan.cpp -o $(OBJDIR)pyVertexSpan.o

$(OBJDIR)pyKey.o: PRP/KeyedObject/pyKey.cpp
	$(CXX) $(CXXFLAGS) -c PRP/KeyedObject/pyKey.cpp -o $(OBJDIR)pyKey.o

$(OBJDIR)pyKeyedObject.o: PRP/KeyedObject/pyKeyedObject.cpp
	$(CXX) $(CXXFLAGS) -c PRP/KeyedObject/pyKeyedObject.cpp -o $(OBJDIR)pyKeyedObject.o

$(OBJDIR)pyLocation.o: PRP/KeyedObject/pyLocation.cpp
	$(CXX) $(CXXFLAGS) -c PRP/KeyedObject/pyLocation.cpp -o $(OBJDIR)pyLocation.o

$(OBJDIR)pyDirectionalLightInfo.o: PRP/Light/pyDirectionalLightInfo.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Light/pyDirectionalLightInfo.cpp -o $(OBJDIR)pyDirectionalLightInfo.o

$(OBJDIR)pyLightInfo.o: PRP/Light/pyLightInfo.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Light/pyLightInfo.cpp -o $(OBJDIR)pyLightInfo.o

$(OBJDIR)pyLimitedDirLightInfo.o: PRP/Light/pyLimitedDirLightInfo.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Light/pyLimitedDirLightInfo.cpp -o $(OBJDIR)pyLimitedDirLightInfo.o

$(OBJDIR)pyOmniLightInfo.o: PRP/Light/pyOmniLightInfo.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Light/pyOmniLightInfo.cpp -o $(OBJDIR)pyOmniLightInfo.o

$(OBJDIR)pySpotLightInfo.o: PRP/Light/pySpotLightInfo.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Light/pySpotLightInfo.cpp -o $(OBJDIR)pySpotLightInfo.o

$(OBJDIR)pyEventCallbackMsg.o: PRP/Message/pyEventCallbackMsg.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Message/pyEventCallbackMsg.cpp -o $(OBJDIR)pyEventCallbackMsg.o

$(OBJDIR)pyMessage.o: PRP/Message/pyMessage.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Message/pyMessage.cpp -o $(OBJDIR)pyMessage.o

$(OBJDIR)pyRenderLevel.o: PRP/Misc/pyRenderLevel.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Misc/pyRenderLevel.cpp -o $(OBJDIR)pyRenderLevel.o

$(OBJDIR)pyModifier.o: PRP/Modifier/pyModifier.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Modifier/pyModifier.cpp -o $(OBJDIR)pyModifier.o

$(OBJDIR)pyMultiModifier.o: PRP/Modifier/pyMultiModifier.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Modifier/pyMultiModifier.cpp -o $(OBJDIR)pyMultiModifier.o

$(OBJDIR)pyOneShotMod.o: PRP/Modifier/pyOneShotMod.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Modifier/pyOneShotMod.cpp -o $(OBJDIR)pyOneShotMod.o

$(OBJDIR)pyPythonFileMod.o: PRP/Modifier/pyPythonFileMod.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Modifier/pyPythonFileMod.cpp -o $(OBJDIR)pyPythonFileMod.o

$(OBJDIR)pyPythonParameter.o: PRP/Modifier/pyPythonParameter.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Modifier/pyPythonParameter.cpp -o $(OBJDIR)pyPythonParameter.o

$(OBJDIR)pyResponderEnableMsg.o: PRP/Modifier/pyResponderEnableMsg.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Modifier/pyResponderEnableMsg.cpp -o $(OBJDIR)pyResponderEnableMsg.o

$(OBJDIR)pyResponderModifier.o: PRP/Modifier/pyResponderModifier.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Modifier/pyResponderModifier.cpp -o $(OBJDIR)pyResponderModifier.o

$(OBJDIR)pyResponderModifier_Cmd.o: PRP/Modifier/pyResponderModifier_Cmd.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Modifier/pyResponderModifier_Cmd.cpp -o $(OBJDIR)pyResponderModifier_Cmd.o

$(OBJDIR)pyResponderModifier_State.o: PRP/Modifier/pyResponderModifier_State.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Modifier/pyResponderModifier_State.cpp -o $(OBJDIR)pyResponderModifier_State.o

$(OBJDIR)pySingleModifier.o: PRP/Modifier/pySingleModifier.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Modifier/pySingleModifier.cpp -o $(OBJDIR)pySingleModifier.o

$(OBJDIR)pyAudioInterface.o: PRP/Object/pyAudioInterface.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Object/pyAudioInterface.cpp -o $(OBJDIR)pyAudioInterface.o

$(OBJDIR)pyCoordinateInterface.o: PRP/Object/pyCoordinateInterface.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Object/pyCoordinateInterface.cpp -o $(OBJDIR)pyCoordinateInterface.o

$(OBJDIR)pyDrawInterface.o: PRP/Object/pyDrawInterface.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Object/pyDrawInterface.cpp -o $(OBJDIR)pyDrawInterface.o

$(OBJDIR)pyObjInterface.o: PRP/Object/pyObjInterface.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Object/pyObjInterface.cpp -o $(OBJDIR)pyObjInterface.o

$(OBJDIR)pySceneObject.o: PRP/Object/pySceneObject.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Object/pySceneObject.cpp -o $(OBJDIR)pySceneObject.o

$(OBJDIR)pySimulationInterface.o: PRP/Object/pySimulationInterface.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Object/pySimulationInterface.cpp -o $(OBJDIR)pySimulationInterface.o

$(OBJDIR)pySynchedObject.o: PRP/Object/pySynchedObject.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Object/pySynchedObject.cpp -o $(OBJDIR)pySynchedObject.o

$(OBJDIR)pyGenericPhysical.o: PRP/Physics/pyGenericPhysical.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Physics/pyGenericPhysical.cpp -o $(OBJDIR)pyGenericPhysical.o

$(OBJDIR)pyPhysical.o: PRP/Physics/pyPhysical.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Physics/pyPhysical.cpp -o $(OBJDIR)pyPhysical.o

$(OBJDIR)pySimDefs.o: PRP/Physics/pySimDefs.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Physics/pySimDefs.cpp -o $(OBJDIR)pySimDefs.o

$(OBJDIR)pyBounds.o: PRP/Region/pyBounds.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Region/pyBounds.cpp -o $(OBJDIR)pyBounds.o

$(OBJDIR)pyBounds3.o: PRP/Region/pyBounds3.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Region/pyBounds3.cpp -o $(OBJDIR)pyBounds3.o

$(OBJDIR)pyBounds3Ext.o: PRP/Region/pyBounds3Ext.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Region/pyBounds3Ext.cpp -o $(OBJDIR)pyBounds3Ext.o

$(OBJDIR)pyBoundsOriented.o: PRP/Region/pyBoundsOriented.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Region/pyBoundsOriented.cpp -o $(OBJDIR)pyBoundsOriented.o

$(OBJDIR)pyBitmap.o: PRP/Surface/pyBitmap.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyBitmap.cpp -o $(OBJDIR)pyBitmap.o

$(OBJDIR)pyGMaterial.o: PRP/Surface/pyGMaterial.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyGMaterial.cpp -o $(OBJDIR)pyGMaterial.o

$(OBJDIR)pyGMatState.o: PRP/Surface/pyGMatState.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyGMatState.cpp -o $(OBJDIR)pyGMatState.o

$(OBJDIR)pyLayer.o: PRP/Surface/pyLayer.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyLayer.cpp -o $(OBJDIR)pyLayer.o

$(OBJDIR)pyLayerAnimation.o: PRP/Surface/pyLayerAnimation.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyLayerAnimation.cpp -o $(OBJDIR)pyLayerAnimation.o

$(OBJDIR)pyLayerAnimationBase.o: PRP/Surface/pyLayerAnimationBase.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyLayerAnimationBase.cpp -o $(OBJDIR)pyLayerAnimationBase.o

$(OBJDIR)pyLayerAVI.o: PRP/Surface/pyLayerAVI.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyLayerAVI.cpp -o $(OBJDIR)pyLayerAVI.o

$(OBJDIR)pyLayerBink.o: PRP/Surface/pyLayerBink.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyLayerBink.cpp -o $(OBJDIR)pyLayerBink.o

$(OBJDIR)pyLayerDepth.o: PRP/Surface/pyLayerDepth.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyLayerDepth.cpp -o $(OBJDIR)pyLayerDepth.o

$(OBJDIR)pyLayerInterface.o: PRP/Surface/pyLayerInterface.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyLayerInterface.cpp -o $(OBJDIR)pyLayerInterface.o

$(OBJDIR)pyLayerLinkAnimation.o: PRP/Surface/pyLayerLinkAnimation.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyLayerLinkAnimation.cpp -o $(OBJDIR)pyLayerLinkAnimation.o

$(OBJDIR)pyLayerMovie.o: PRP/Surface/pyLayerMovie.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyLayerMovie.cpp -o $(OBJDIR)pyLayerMovie.o

$(OBJDIR)pyLayerSDLAnimation.o: PRP/Surface/pyLayerSDLAnimation.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyLayerSDLAnimation.cpp -o $(OBJDIR)pyLayerSDLAnimation.o

$(OBJDIR)pyMipmap.o: PRP/Surface/pyMipmap.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyMipmap.cpp -o $(OBJDIR)pyMipmap.o

$(OBJDIR)pyShader.o: PRP/Surface/pyShader.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyShader.cpp -o $(OBJDIR)pyShader.o

$(OBJDIR)pyShaderConst.o: PRP/Surface/pyShaderConst.cpp
	$(CXX) $(CXXFLAGS) -c PRP/Surface/pyShaderConst.cpp -o $(OBJDIR)pyShaderConst.o

$(OBJDIR)pyAgeInfo.o: ResManager/pyAgeInfo.cpp
	$(CXX) $(CXXFLAGS) -c ResManager/pyAgeInfo.cpp -o $(OBJDIR)pyAgeInfo.o

$(OBJDIR)pyFactory.o: ResManager/pyFactory.cpp
	$(CXX) $(CXXFLAGS) -c ResManager/pyFactory.cpp -o $(OBJDIR)pyFactory.o

$(OBJDIR)pyResManager.o: ResManager/pyResManager.cpp
	$(CXX) $(CXXFLAGS) -c ResManager/pyResManager.cpp -o $(OBJDIR)pyResManager.o

$(OBJDIR)pyPageInfo.o: ResManager/pyPageInfo.cpp
	$(CXX) $(CXXFLAGS) -c ResManager/pyPageInfo.cpp -o $(OBJDIR)pyPageInfo.o

$(OBJDIR)pyEncryptedStream.o: Stream/pyEncryptedStream.cpp
	$(CXX) $(CXXFLAGS) -c Stream/pyEncryptedStream.cpp -o $(OBJDIR)pyEncryptedStream.o

$(OBJDIR)pyFileStream.o: Stream/pyFileStream.cpp
	$(CXX) $(CXXFLAGS) -c Stream/pyFileStream.cpp -o $(OBJDIR)pyFileStream.o

$(OBJDIR)pyStream.o: Stream/pyStream.cpp
	$(CXX) $(CXXFLAGS) -c Stream/pyStream.cpp -o $(OBJDIR)pyStream.o

$(OBJDIR)pyColor32.o: Sys/pyColor32.cpp
	$(CXX) $(CXXFLAGS) -c Sys/pyColor32.cpp -o $(OBJDIR)pyColor32.o

$(OBJDIR)pyColorRGBA.o: Sys/pyColorRGBA.cpp
	$(CXX) $(CXXFLAGS) -c Sys/pyColorRGBA.cpp -o $(OBJDIR)pyColorRGBA.o

$(OBJDIR)pyBitVector.o: Util/pyBitVector.cpp
	$(CXX) $(CXXFLAGS) -c Util/pyBitVector.cpp -o $(OBJDIR)pyBitVector.o
